name: Sync
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: github-proxy
      - name: Synchronize
        run: |
          git config user.email "fushen@mail.ustc.edu.cn" && \
          git config user.name "Fr4nk1in" && \
          git rebase origin/master
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: github-proxy
          force_with_lease: true
