name: "Bundle minivim on x86-64 Linux"
on:
  # push:
  # pull_request:
  workflow_dispatch:
jobs:
  bundle:
    name: Build minivim, bundle a AppImage and upload it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix bundle --bundler github:ralismark/nix-appimage ".#minivim"
      - run: cp "$(readlink minivim.AppImage)" /tmp/minivim.AppImage
      - uses: actions/upload-artifact@v4
        with:
          name: minivim.AppImage
          path: /tmp/minivim.AppImage
          retention-days: 1
          compression-level: 0
